const data = [
  {
    id: 1,
    name: "Babar Azam",
    dob: "15 October",
    age: 28,
    image: "https://i.ibb.co/gTQMvGx/babar-azam.jpg",
  },
  {
    id: 2,
    name: "Taskin Ahmed",
    dob: "03 April",
    age: 27,
    image: "https://i.ibb.co/By6wCZN/taskin.jpg",
  },
  {
    id: 3,
    name: "Sania Mirza",
    dob: "15 November",
    age: 35,
    image: "https://i.ibb.co/QmTZhxk/sania.jpg",
  },
  {
    id: 4,
    name: "Shahid Afridi",
    dob: "01 March",
    age: 42,
    image: "https://i.ibb.co/0m7XwVX/shahid-afridi.jpg",
  },
  {
    id: 5,
    name: "Maria Sharapova",
    dob: "19 April",
    age: 35,
    image: "https://i.ibb.co/tBVf35T/sharapova.jpg",
  },
  {
    id: 6,
    name: "Christiano Ronaldo",
    dob: "05 February",
    age: 37,
    image: "https://i.ibb.co/Rbwm2FH/ronaldo.jpg",
  },
  {
    id: 7,
    name: "Tamim Iqbal",
    dob: "20 March",
    age: 33,
    image: "https://i.ibb.co/HYh2VKc/tamim.jpg",
  },
  {
    id: 8,
    name: "Katherine Langford",
    dob: "29 April",
    age: 26,
    image: "https://i.ibb.co/Y37zHkd/katherine-langford.jpg",
  },
  {
    id: 9,
    name: "Litton Das",
    dob: "13 October",
    age: 28,
    image: "https://i.ibb.co/rvm7vxL/liton.jpg",
  },
  {
    id: 10,
    name: "Alexandra Daddario",
    dob: "16 March",
    age: 36,
    image: "https://i.ibb.co/bgyVXfz/alexandra-daddario.jpg",
  },
  {
    id: 11,
    name: "Neymar Junior",
    dob: "05 February",
    age: 30,
    image: "https://i.ibb.co/r5FDcvY/neymar.jpg",
  },
  {
    id: 12,
    name: "Leonel Messi",
    dob: "24 June",
    age: 35,
    image: "https://i.ibb.co/02rkwVr/messi.jpg",
  },
  {
    id: 13,
    name: "Mashrafe Mortaza",
    dob: "05 October",
    age: 39,
    image: "https://i.ibb.co/smCwgSx/mashrafee.jpg",
  },
  {
    id: 14,
    name: "Usain Bolt",
    dob: "21 August",
    age: 36,
    image: "https://i.ibb.co/55WVK7f/usain.jpg",
  },
  {
    id: 15,
    name: "Roger Federar",
    dob: "08 August",
    age: 41,
    image: "https://i.ibb.co/K6wbYbZ/roger-federar.jpg",
  },
];

export default data;
